apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
  labels:
    app: conversaotemperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
      - name: conversao
        image: agnelo502/conversao-temperatura:v2
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
