apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec:
  #type: NodePort
  selector:
    app: conversaotemperatura
  ports:
    - port: 8080
      #targetPort: 8080
      #nodePort: 30000